
const fs = require('fs');
const path = require('path');

const target = path.join(__dirname, 'mobile', 'components', 'RealisticMoon.js');

const lines = [];
function L(s) { lines.push(s); }

// Imports
L("import React, { useEffect, useRef, useMemo, useCallback } from 'react';");
L("import { View, Platform } from 'react-native';");
L("import Svg, { Circle, Defs, RadialGradient, Stop, Path, G, ClipPath } from 'react-native-svg';");
L("import Animated, { useSharedValue, useAnimatedStyle, withRepeat, withTiming, withSequence, interpolate, Easing } from 'react-native-reanimated';");
L("");

// Texture cache
L("var cachedColorPixels = null;");
L("var cachedNormPixels = null;");
L("var TWIDTH = 512;");
L("var THEIGHT = 256;");
L("");

// Seeded PRNG
L("var _rngState = 42;");
L("function _nextRand() {");
L("  _rngState = (_rngState * 16807) % 2147483647;");
L("  return (_rngState - 1) / 2147483646;");
L("}");
L("function _resetRng() { _rngState = 42; }");
L("");

// Procedural moon color texture
L("function buildLunarColorMap() {");
L("  if (cachedColorPixels) return cachedColorPixels;");
L("  _resetRng();");
L("  var w = TWIDTH, h = THEIGHT;");
L("  var px = new Uint8Array(w * h * 4);");
L("");
L("  // Pre-generate crater definitions");
L("  var numCraters = 200;");
L("  var craterList = [];");
L("  for (var ci = 0; ci < numCraters; ci++) {");
L("    var cRadius;");
L("    if (ci < 6) cRadius = 14 + _nextRand() * 22;");
L("    else if (ci < 25) cRadius = 6 + _nextRand() * 12;");
L("    else if (ci < 70) cRadius = 2 + _nextRand() * 5;");
L("    else cRadius = 0.8 + _nextRand() * 2.5;");
L("    craterList.push({");
L("      px: _nextRand() * w, py: _nextRand() * h,");
L("      rad: cRadius,");
L("      dep: 0.10 + _nextRand() * 0.25,");
L("      rim: 0.03 + _nextRand() * 0.09");
L("    });");
L("  }");
L("");
L("  // Dark plains (maria) regions");
L("  var darkPlains = [");
L("    {cx:0.38,cy:0.35,rx:0.13,ry:0.11,strength:0.17},");
L("    {cx:0.55,cy:0.40,rx:0.10,ry:0.09,strength:0.15},");
L("    {cx:0.60,cy:0.50,rx:0.11,ry:0.09,strength:0.14},");
L("    {cx:0.28,cy:0.52,rx:0.12,ry:0.18,strength:0.12},");
L("    {cx:0.48,cy:0.63,rx:0.10,ry:0.07,strength:0.11},");
L("    {cx:0.72,cy:0.42,rx:0.06,ry:0.05,strength:0.16},");
L("    {cx:0.66,cy:0.56,rx:0.08,ry:0.06,strength:0.12},");
L("    {cx:0.34,cy:0.71,rx:0.06,ry:0.05,strength:0.13},");
L("    {cx:0.43,cy:0.46,rx:0.07,ry:0.11,strength:0.11},");
L("    {cx:0.24,cy:0.38,rx:0.08,ry:0.06,strength:0.10},");
L("  ];");
L("");
L("  for (var row = 0; row < h; row++) {");
L("    for (var col = 0; col < w; col++) {");
L("      var offset = (row * w + col) * 4;");
L("      // Base highland brightness with subtle variation");
L("      var bright = 0.72 + _nextRand() * 0.04;");
L("      // Low frequency terrain undulation");
L("      var angX = col / w * 6.283;");
L("      var angY = row / h * 3.142;");
L("      bright += Math.sin(angX * 2.3 + angY * 1.7) * 0.028;");
L("      bright += Math.sin(angX * 5.1 - angY * 3.3) * 0.020;");
L("      bright += Math.sin(angX * 0.8 + angY * 4.2) * 0.016;");
L("      bright += Math.sin(angX * 8.5 + angY * 6.1) * 0.008;");
L("");
L("      // Apply dark plains");
L("      for (var pi = 0; pi < darkPlains.length; pi++) {");
L("        var dp = darkPlains[pi];");
L("        var fx = (col / w - dp.cx) / dp.rx;");
L("        var fy = (row / h - dp.cy) / dp.ry;");
L("        var fdist2 = fx * fx + fy * fy;");
L("        if (fdist2 < 1) {");
L("          var falloff = 1 - Math.sqrt(fdist2);");
L("          bright -= dp.strength * falloff * falloff;");
L("        }");
L("      }");
L("");
L("      // Apply craters");
L("      for (var ki = 0; ki < craterList.length; ki++) {");
L("        var cr = craterList[ki];");
L("        var dx = col - cr.px;");
L("        var dy = row - cr.py;");
L("        // Wrap horizontally for seamless tiling");
L("        if (dx > w / 2) dx -= w;");
L("        if (dx < -w / 2) dx += w;");
L("        var dist = Math.sqrt(dx * dx + dy * dy);");
L("        if (dist < cr.rad * 1.35) {");
L("          var normDist = dist / cr.rad;");
L("          if (normDist < 0.75) {");
L("            bright -= cr.dep * (1 - normDist / 0.75) * 0.5;");
L("          } else if (normDist < 1.0) {");
L("            bright -= cr.dep * 0.08 * (1 - (normDist - 0.75) / 0.25);");
L("          } else if (normDist < 1.25) {");
L("            bright += cr.rim * (1 - (normDist - 1.0) / 0.25);");
L("          }");
L("        }");
L("      }");
L("");
L("      // Micro-noise for grain");
L("      bright += (_nextRand() - 0.5) * 0.018;");
L("      bright = Math.max(0.04, Math.min(0.97, bright));");
L("");
L("      // Slightly warm-tinted gray (like real regolith)");
L("      px[offset]     = Math.floor(bright * 228);");
L("      px[offset + 1] = Math.floor(bright * 220);");
L("      px[offset + 2] = Math.floor(bright * 206);");
L("      px[offset + 3] = 255;");
L("    }");
L("  }");
L("  cachedColorPixels = px;");
L("  return px;");
L("}");
L("");

// Normal map generation
L("function buildLunarNormalMap() {");
L("  if (cachedNormPixels) return cachedNormPixels;");
L("  var colorPx = buildLunarColorMap();");
L("  var w = TWIDTH, h = THEIGHT;");
L("  var norms = new Uint8Array(w * h * 4);");
L("  var bumpStrength = 2.5;");
L("  for (var row = 0; row < h; row++) {");
L("    for (var col = 0; col < w; col++) {");
L("      var off = (row * w + col) * 4;");
L("      var heightL = colorPx[(row * w + ((col - 1 + w) % w)) * 4] / 255;");
L("      var heightR = colorPx[(row * w + ((col + 1) % w)) * 4] / 255;");
L("      var heightU = colorPx[(Math.max(row - 1, 0) * w + col) * 4] / 255;");
L("      var heightD = colorPx[(Math.min(row + 1, h - 1) * w + col) * 4] / 255;");
L("      var gradX = (heightL - heightR) * bumpStrength;");
L("      var gradY = (heightU - heightD) * bumpStrength;");
L("      var gradZ = 1.0;");
L("      var mag = Math.sqrt(gradX * gradX + gradY * gradY + gradZ * gradZ);");
L("      norms[off]     = Math.floor(((gradX / mag) * 0.5 + 0.5) * 255);");
L("      norms[off + 1] = Math.floor(((gradY / mag) * 0.5 + 0.5) * 255);");
L("      norms[off + 2] = Math.floor(((gradZ / mag) * 0.5 + 0.5) * 255);");
L("      norms[off + 3] = 255;");
L("    }");
L("  }");
L("  cachedNormPixels = norms;");
L("  return norms;");
L("}");
L("");

// computeLightAngle helper
L("function computeLightAngle(tithiNum) {");
L("  return ((tithiNum - 1) / 29) * Math.PI * 2;");
L("}");
L("");
L("function computeIllumFraction(tithiNum) {");
L("  return (1 - Math.cos(computeLightAngle(tithiNum))) / 2;");
L("}");
L("");

// 3D scene builder
L("function assembleMoonScene(THREE, rendererObj, sunAngle, shouldAnimate, stateHolder) {");
L("  var scene = new THREE.Scene();");
L("  var cam = new THREE.PerspectiveCamera(32, 1, 0.1, 100);");
L("  cam.position.z = 3.2;");
L("");
L("  var colorBytes = buildLunarColorMap();");
L("  var colorDataTex = new THREE.DataTexture(colorBytes, TWIDTH, THEIGHT, THREE.RGBAFormat);");
L("  colorDataTex.needsUpdate = true;");
L("  colorDataTex.wrapS = THREE.RepeatWrapping;");
L("  colorDataTex.wrapT = THREE.ClampToEdgeWrapping;");
L("  colorDataTex.magFilter = THREE.LinearFilter;");
L("  colorDataTex.minFilter = THREE.LinearMipmapLinearFilter;");
L("  colorDataTex.generateMipmaps = true;");
L("");
L("  var normBytes = buildLunarNormalMap();");
L("  var normDataTex = new THREE.DataTexture(normBytes, TWIDTH, THEIGHT, THREE.RGBAFormat);");
L("  normDataTex.needsUpdate = true;");
L("  normDataTex.wrapS = THREE.RepeatWrapping;");
L("  normDataTex.wrapT = THREE.ClampToEdgeWrapping;");
L("  normDataTex.magFilter = THREE.LinearFilter;");
L("  normDataTex.minFilter = THREE.LinearMipmapLinearFilter;");
L("  normDataTex.generateMipmaps = true;");
L("");
L("  var sphereGeo = new THREE.SphereGeometry(1, 64, 48);");
L("  var surfaceMat = new THREE.MeshPhongMaterial({");
L("    map: colorDataTex,");
L("    normalMap: normDataTex,");
L("    normalScale: new THREE.Vector2(1.0, 1.0),");
L("    bumpMap: colorDataTex,");
L("    bumpScale: 0.015,");
L("    shininess: 4,");
L("    specular: new THREE.Color(0x222222),");
L("    emissive: new THREE.Color(0x030306),");
L("  });");
L("  var moonMesh = new THREE.Mesh(sphereGeo, surfaceMat);");
L("  moonMesh.rotation.x = 0.15;");
L("  scene.add(moonMesh);");
L("  stateHolder.moonMesh = moonMesh;");
L("");
L("  var sx = Math.sin(sunAngle) * 5;");
L("  var sz = Math.cos(sunAngle) * 5;");
L("");
L("  var mainSun = new THREE.DirectionalLight(0xFFF5E0, 2.0);");
L("  mainSun.position.set(sx, 0.3, sz);");
L("  scene.add(mainSun);");
L("  stateHolder.mainSun = mainSun;");
L("");
L("  var reflectedEarth = new THREE.DirectionalLight(0x334488, 0.07);");
L("  reflectedEarth.position.set(-sx, -0.2, -sz);");
L("  scene.add(reflectedEarth);");
L("  stateHolder.reflectedEarth = reflectedEarth;");
L("");
L("  var ambientFill = new THREE.AmbientLight(0x0A0A1E, 0.18);");
L("  scene.add(ambientFill);");
L("");
L("  stateHolder.sceneObj = scene;");
L("  stateHolder.camObj = cam;");
L("  stateHolder.rendererObj = rendererObj;");
L("  stateHolder.spinY = 0;");
L("}");
L("");

// Light update
L("function repositionLights(stateHolder, sunAngle) {");
L("  if (!stateHolder.mainSun) return;");
L("  var sx = Math.sin(sunAngle) * 5;");
L("  var sz = Math.cos(sunAngle) * 5;");
L("  stateHolder.mainSun.position.set(sx, 0.3, sz);");
L("  if (stateHolder.reflectedEarth) stateHolder.reflectedEarth.position.set(-sx, -0.2, -sz);");
L("}");
L("");

// ========== WEB 3D MOON ==========
L("function MoonCanvasWeb({ size, tithiNum, animate }) {");
L("  var boxRef = useRef(null);");
L("  var state = useRef({}).current;");
L("  var rafRef = useRef(null);");
L("");
L("  var sunAngle = useMemo(function() { return computeLightAngle(tithiNum); }, [tithiNum]);");
L("  var dpr = typeof window !== 'undefined' ? (window.devicePixelRatio || 1) : 1;");
L("  var pxSize = Math.floor(size * dpr);");
L("");
L("  useEffect(function() {");
L("    var box = boxRef.current;");
L("    if (!box) return;");
L("    var THREE;");
L("    try { THREE = require('three'); } catch(e) { return; }");
L("");
L("    var cvs = document.createElement('canvas');");
L("    cvs.width = pxSize;");
L("    cvs.height = pxSize;");
L("    cvs.style.width = size + 'px';");
L("    cvs.style.height = size + 'px';");
L("    cvs.style.borderRadius = '50%';");
L("    cvs.style.display = 'block';");
L("    box.innerHTML = '';");
L("    box.appendChild(cvs);");
L("");
L("    var glRenderer = new THREE.WebGLRenderer({ canvas: cvs, antialias: true, alpha: true });");
L("    glRenderer.setSize(pxSize, pxSize, false);");
L("    glRenderer.setPixelRatio(1);");
L("    glRenderer.setClearColor(0x000000, 0);");
L("");
L("    assembleMoonScene(THREE, glRenderer, sunAngle, animate, state);");
L("");
L("    function tick() {");
L("      rafRef.current = requestAnimationFrame(tick);");
L("      if (animate && state.moonMesh) {");
L("        state.spinY += 0.0006;");
L("        state.moonMesh.rotation.y = state.spinY;");
L("      }");
L("      glRenderer.render(state.sceneObj, state.camObj);");
L("    }");
L("    tick();");
L("");
L("    return function() {");
L("      if (rafRef.current) cancelAnimationFrame(rafRef.current);");
L("      glRenderer.dispose();");
L("      if (box) box.innerHTML = '';");
L("    };");
L("  }, [size, pxSize]);");
L("");
L("  useEffect(function() { repositionLights(state, sunAngle); }, [sunAngle]);");
L("");
L("  var illum = computeIllumFraction(tithiNum);");
L("  var glowR = Math.round(illum * 20 + 4);");
L("  var glowA = (illum * 0.5 + 0.1).toFixed(2);");
L("");
L("  return (");
L("    <div ref={boxRef} style={{");
L("      width: size, height: size, borderRadius: '50%', overflow: 'hidden',");
L("      boxShadow: '0 0 ' + glowR + 'px ' + Math.round(glowR * 0.6) + 'px rgba(200,195,230,' + glowA + ')',");
L("      background: '#020208',");
L("    }} />");
L("  );");
L("}");
L("");

// ========== NATIVE 3D MOON ==========
L("var _nativeGLView = null;");
L("var _nativeTHREE = null;");
L("var _nativeReady = false;");
L("var _nativeChecked = false;");
L("");
L("function ensureNativeModules() {");
L("  if (_nativeChecked) return _nativeReady;");
L("  _nativeChecked = true;");
L("  try {");
L("    _nativeTHREE = require('three');");
L("    _nativeGLView = require('expo-gl').GLView;");
L("    _nativeReady = true;");
L("  } catch(e) { _nativeReady = false; }");
L("  return _nativeReady;");
L("}");
L("");
L("function MoonGLNative({ size, tithiNum, animate }) {");
L("  var state = useRef({}).current;");
L("  var rafRef = useRef(null);");
L("");
L("  var sunAngle = useMemo(function() { return computeLightAngle(tithiNum); }, [tithiNum]);");
L("");
L("  var handleGLReady = useCallback(function(gl) {");
L("    var THREE = _nativeTHREE;");
L("    var canvasShim = {");
L("      width: gl.drawingBufferWidth,");
L("      height: gl.drawingBufferHeight,");
L("      style: {},");
L("      addEventListener: function() {},");
L("      removeEventListener: function() {},");
L("      clientHeight: gl.drawingBufferHeight,");
L("    };");
L("    var glRenderer = new THREE.WebGLRenderer({");
L("      canvas: canvasShim, context: gl, antialias: true,");
L("    });");
L("    glRenderer.setSize(gl.drawingBufferWidth, gl.drawingBufferHeight);");
L("    glRenderer.setPixelRatio(1);");
L("    glRenderer.setClearColor(0x000000, 0);");
L("");
L("    assembleMoonScene(THREE, glRenderer, sunAngle, animate, state);");
L("");
L("    function tick() {");
L("      rafRef.current = requestAnimationFrame(tick);");
L("      if (animate && state.moonMesh) {");
L("        state.spinY += 0.0006;");
L("        state.moonMesh.rotation.y = state.spinY;");
L("      }");
L("      glRenderer.render(state.sceneObj, state.camObj);");
L("      gl.endFrameEXP();");
L("    }");
L("    tick();");
L("  }, [sunAngle, animate]);");
L("");
L("  useEffect(function() { repositionLights(state, sunAngle); }, [sunAngle]);");
L("");
L("  useEffect(function() {");
L("    return function() {");
L("      if (rafRef.current) cancelAnimationFrame(rafRef.current);");
L("      if (state.rendererObj) { state.rendererObj.dispose(); state.rendererObj = null; }");
L("    };");
L("  }, []);");
L("");
L("  var pulse = useSharedValue(0);");
L("  useEffect(function() {");
L("    if (animate) {");
L("      pulse.value = withRepeat(withSequence(");
L("        withTiming(1, { duration: 3500, easing: Easing.inOut(Easing.sin) }),");
L("        withTiming(0, { duration: 3500, easing: Easing.inOut(Easing.sin) })");
L("      ), -1, true);");
L("    }");
L("  }, [animate]);");
L("");
L("  var illum = computeIllumFraction(tithiNum);");
L("  var glowStyle = useAnimatedStyle(function() {");
L("    var gr = interpolate(pulse.value, [0, 1], [8, 22]) * illum;");
L("    var ga = interpolate(pulse.value, [0, 1], [0.2, 0.5]) * illum;");
L("    return {");
L("      shadowColor: illum > 0.5 ? '#D8D0FF' : '#9088C0',");
L("      shadowOffset: { width: 0, height: 0 },");
L("      shadowOpacity: ga,");
L("      shadowRadius: gr,");
L("      elevation: 0,");
L("    };");
L("  });");
L("");
L("  var NativeGL = _nativeGLView;");
L("  return (");
L("    <Animated.View style={[{");
L("      width: size, height: size, borderRadius: size / 2,");
L("      overflow: 'hidden', backgroundColor: '#020208',");
L("    }, animate && glowStyle]}>");
L("      <NativeGL style={{ width: size, height: size }} onContextCreate={handleGLReady} msaaSamples={4} />");
L("    </Animated.View>");
L("  );");
L("}");
L("");

// ========== SMALL SVG MOON ==========
L("function TinyMoonSVG({ size, tithiNum }) {");
L("  var mid = size / 2;");
L("  var R = size * 0.42;");
L("  var angle = computeLightAngle(tithiNum);");
L("  var illum = computeIllumFraction(tithiNum);");
L("");
L("  // Full moon");
L("  if (illum > 0.997) {");
L("    return (");
L("      <Svg width={size} height={size} viewBox={'0 0 ' + size + ' ' + size}>");
L("        <Defs>");
L("          <RadialGradient id='tfg' cx='42%' cy='40%' r='58%'>");
L("            <Stop offset='0%' stopColor='#EAE4D8' />");
L("            <Stop offset='60%' stopColor='#D8D0C4' />");
L("            <Stop offset='100%' stopColor='#C0B8AC' />");
L("          </RadialGradient>");
L("        </Defs>");
L("        <Circle cx={mid} cy={mid} r={R} fill='url(#tfg)' />");
L("        <Circle cx={mid * 0.85} cy={mid * 0.80} r={R * 0.22} fill='rgba(140,132,122,0.28)' />");
L("        <Circle cx={mid * 1.2} cy={mid * 0.70} r={R * 0.14} fill='rgba(140,132,122,0.22)' />");
L("        <Circle cx={mid * 0.75} cy={mid * 1.15} r={R * 0.17} fill='rgba(140,132,122,0.20)' />");
L("      </Svg>");
L("    );");
L("  }");
L("");
L("  // New moon");
L("  if (illum < 0.003) {");
L("    return (");
L("      <Svg width={size} height={size} viewBox={'0 0 ' + size + ' ' + size}>");
L("        <Circle cx={mid} cy={mid} r={R} fill='#12101E' />");
L("        <Circle cx={mid} cy={mid} r={R} fill='rgba(70,90,130,0.06)' />");
L("      </Svg>");
L("    );");
L("  }");
L("");
L("  // Partial phase");
L("  var terminatorBulge = Math.cos(angle) * R;");
L("  var waxing = tithiNum <= 15;");
L("  var topY = mid - R;");
L("  var botY = mid + R;");
L("  var absT = Math.max(Math.abs(terminatorBulge), 0.5);");
L("  var litArc;");
L("  if (waxing) {");
L("    var sweepFlag = terminatorBulge > 0 ? 0 : 1;");
L("    litArc = 'M ' + mid + ' ' + topY + ' A ' + R + ' ' + R + ' 0 0 1 ' + mid + ' ' + botY + ' A ' + absT + ' ' + R + ' 0 0 ' + sweepFlag + ' ' + mid + ' ' + topY + ' Z';");
L("  } else {");
L("    var sweepFlag2 = terminatorBulge > 0 ? 1 : 0;");
L("    litArc = 'M ' + mid + ' ' + topY + ' A ' + R + ' ' + R + ' 0 0 0 ' + mid + ' ' + botY + ' A ' + absT + ' ' + R + ' 0 0 ' + sweepFlag2 + ' ' + mid + ' ' + topY + ' Z';");
L("  }");
L("  var uid = 'tm' + size + 'p' + tithiNum;");
L("  return (");
L("    <Svg width={size} height={size} viewBox={'0 0 ' + size + ' ' + size}>");
L("      <Defs>");
L("        <ClipPath id={uid + 'disc'}><Circle cx={mid} cy={mid} r={R} /></ClipPath>");
L("        <ClipPath id={uid + 'lit'}><Path d={litArc} /></ClipPath>");
L("        <RadialGradient id={uid + 'rg'} cx='42%' cy='40%' r='58%'>");
L("          <Stop offset='0%' stopColor='#EAE4D8' />");
L("          <Stop offset='60%' stopColor='#D8D0C4' />");
L("          <Stop offset='100%' stopColor='#C0B8AC' />");
L("        </RadialGradient>");
L("      </Defs>");
L("      <G clipPath={'url(#' + uid + 'disc)'}>");
L("        <Circle cx={mid} cy={mid} r={R} fill='#12101E' />");
L("        <Path d={litArc} fill={'url(#' + uid + 'rg)'} />");
L("        <G clipPath={'url(#' + uid + 'lit)'}>");
L("          <Circle cx={mid * 0.85} cy={mid * 0.80} r={R * 0.22} fill='rgba(140,132,122,0.28)' />");
L("          <Circle cx={mid * 1.2} cy={mid * 0.70} r={R * 0.14} fill='rgba(140,132,122,0.22)' />");
L("        </G>");
L("        <Circle cx={mid} cy={mid} r={R} fill='none' stroke='rgba(20,15,40,0.30)' strokeWidth={R * 0.12} />");
L("      </G>");
L("    </Svg>");
L("  );");
L("}");
L("");

// ========== MAIN EXPORT ==========
L("export default function RealisticMoon({ size, tithiNum, animate }) {");
L("  if (size === undefined) size = 160;");
L("  if (tithiNum === undefined) tithiNum = 8;");
L("  if (animate === undefined) animate = true;");
L("");
L("  // Tiny thumbnails: use lightweight SVG on all platforms");
L("  if (size < 60) {");
L("    return <TinyMoonSVG size={size} tithiNum={tithiNum} />;");
L("  }");
L("");
L("  // Web: HTML canvas element + Three.js WebGLRenderer directly");
L("  if (Platform.OS === 'web') {");
L("    return <MoonCanvasWeb size={size} tithiNum={tithiNum} animate={animate} />;");
L("  }");
L("");
L("  // Native (iOS/Android): expo-gl GLView + Three.js");
L("  if (ensureNativeModules()) {");
L("    return <MoonGLNative size={size} tithiNum={tithiNum} animate={animate} />;");
L("  }");
L("");
L("  // Absolute fallback");
L("  return <TinyMoonSVG size={size} tithiNum={tithiNum} />;");
L("}");

fs.writeFileSync(target, lines.join('\n'), 'utf8');
console.log('Wrote RealisticMoon.js — ' + lines.length + ' lines');
